import mongoose from 'mongoose';
import dotenv from 'dotenv';
import path from 'path';
import fs from 'fs';
import { fileURLToPath } from 'url';
import Note from '../models/Note.model.js';
import { v4 as uuidv4 } from 'uuid';
import PDFDocument from 'pdfkit';
import axios from 'axios';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

dotenv.config({ path: path.join(__dirname, '../../.env') });

const NEW_BANK_PATH = path.join(__dirname, '../../../question_bank.json');
const UPLOADS_DIR = path.join(__dirname, '../../uploads/notes');

async function fetchWikipediaExtract(topic) {
  try {
    const res = await axios.get(`https://en.wikipedia.org/w/api.php?action=query&prop=extracts&exintro&titles=${encodeURIComponent(topic)}&format=json`, {
      headers: { 'User-Agent': 'PrepzoApp/1.0' },
      timeout: 5000
    });
    const pages = res.data.query.pages;
    const pageId = Object.keys(pages)[0];
    if (pageId !== '-1' && pages[pageId].extract) {
      return pages[pageId].extract.replace(/<[^>]+>/g, '').trim();
    }
  } catch (e) {
    console.log(`Failed to fetch Wikipedia for ${topic}`);
  }
  return null;
}

async function createPDF(filePath, title, category, subSkill, difficulty, extract) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });
    const stream = fs.createWriteStream(filePath);
    doc.pipe(stream);

    // Title
    doc.fontSize(24).fillColor('#3b82f6').text(title, { align: 'center' });
    doc.moveDown();

    // Meta
    doc.fontSize(12).fillColor('#666666')
       .text(`Category: ${category} | Topic: ${subSkill} | Level: ${difficulty}`, { align: 'center' });
    doc.moveDown(2);

    // Intro
    doc.fontSize(16).fillColor('#000000').text('Introduction');
    doc.moveDown(0.5);
    
    if (extract) {
      doc.fontSize(12).text(extract, { align: 'justify', lineGap: 5 });
    } else {
      doc.fontSize(12).text(`This comprehensive guide covers the essential concepts, principles, and real-world applications of ${subSkill}. As a crucial component of modern development, mastering ${subSkill} is highly recommended for any professional aiming for a ${difficulty} level role.`, { align: 'justify', lineGap: 5 });
    }
    doc.moveDown(2);

    // Additional Sections
    doc.fontSize(16).fillColor('#000000').text('Key Concepts & Best Practices');
    doc.moveDown(0.5);
    doc.fontSize(12).text(`When working with ${subSkill}, there are several best practices to keep in mind:\n\n1. Always understand the core mechanics before relying on advanced abstractions.\n2. Keep security and performance at the forefront of your design.\n3. Regularly consult the official documentation for the latest updates.\n4. Practice by building real-world scenarios rather than just reading theory.`, { align: 'justify', lineGap: 5 });
    doc.moveDown(2);

    doc.fontSize(16).fillColor('#000000').text('Common Interview Focus Areas');
    doc.moveDown(0.5);
    doc.fontSize(12).text(`For a ${difficulty} position, interviewers will typically expect you to explain not just how to use ${subSkill}, but why it works the way it does. You may be asked to optimize existing solutions, debug common pitfalls, and explain trade-offs compared to alternative approaches.`, { align: 'justify', lineGap: 5 });
    doc.moveDown(2);

    // Footer
    doc.fontSize(10).fillColor('#999999').text('Generated by AI Career Platform - Study Materials', 50, doc.page.height - 50, { align: 'center' });

    doc.end();
    stream.on('finish', resolve);
    stream.on('error', reject);
  });
}

const seedNotes = async () => {
  try {
    const mongoUri = process.env.MONGODB_URI;
    if (!mongoUri) throw new Error('MONGODB_URI not found in .env');

    await mongoose.connect(mongoUri);
    console.log('Connected to MongoDB Database:', mongoose.connection.name);

    await Note.deleteMany({});
    console.log('Cleared existing notes');

    // Create uploads directory if it doesn't exist
    if (!fs.existsSync(UPLOADS_DIR)) {
      fs.mkdirSync(UPLOADS_DIR, { recursive: true });
    }

    const notesToInsert = [];
    const baseUrl = process.env.NODE_ENV === 'production' 
      ? 'https://your-production-url.com' // Replace with actual domain in production
      : `http://localhost:${process.env.PORT || 5000}`;

    if (fs.existsSync(NEW_BANK_PATH)) {
      console.log('Processing question bank to generate notes and PDFs...');
      const data = JSON.parse(fs.readFileSync(NEW_BANK_PATH, 'utf8'));
      const categories = data.question_bank.categories;

      // Cache extracts to avoid refetching the same topic 3 times
      const extractCache = {};

      for (const [categoryName, subSkills] of Object.entries(categories)) {
        for (const subSkillName of Object.keys(subSkills)) {
          
          if (!extractCache[subSkillName]) {
            console.log(`Fetching Wikipedia content for: ${subSkillName}`);
            extractCache[subSkillName] = await fetchWikipediaExtract(subSkillName);
          }
          const extract = extractCache[subSkillName];

          // Generate 3 notes for each subskill
          for (let i = 1; i <= 3; i++) {
            const difficulties = ['beginner', 'intermediate', 'advanced'];
            const difficulty = difficulties[i - 1];
            const noteId = uuidv4();
            const fileName = `${noteId}.pdf`;
            const filePath = path.join(UPLOADS_DIR, fileName);
            const title = `${subSkillName} - Comprehensive Guide Part ${i}`;

            await createPDF(filePath, title, categoryName, subSkillName, difficulty, extract);
            
            const fileUrl = `${baseUrl}/uploads/notes/${fileName}`;

            notesToInsert.push({
              noteId: noteId,
              title: title,
              category: categoryName,
              subSkill: subSkillName,
              summary: extract 
                ? `Learn all about ${subSkillName} in this in-depth guide covering key concepts. Perfect for ${difficulty} level students.` 
                : `This is a comprehensive study guide covering the essential concepts, principles, and applications of ${subSkillName}. Perfect for ${difficulty} level students preparing for interviews.`,
              content: fileUrl,
              difficulty: difficulty,
              readTimeMinutes: Math.floor(Math.random() * 15) + 5, // 5 to 20 minutes
              tags: [subSkillName.toLowerCase().replace(/ /g, '-'), 'study-material', 'interview-prep', difficulty]
            });
          }
        }
      }
    }

    if (notesToInsert.length > 0) {
      await Note.insertMany(notesToInsert);
      console.log(`✅ Successfully seeded ${notesToInsert.length} study notes with actual PDFs`);
    } else {
      console.log('⚠️ No subskills found to generate notes for.');
    }

    process.exit(0);
  } catch (error) {
    console.error('Seeding failed:', error);
    process.exit(1);
  }
};

seedNotes();
